# Site settings
title: Biligunb
email: biligunb@gmail.com
url: https://biligunb.github.io
description: "biligunb's online resume. 2B +1% better 2day cv.001"
keywords: "biligunb, resume, cv, cover letter, interview, developer, engineer, programmer, researcher"
skills: "Web Developer - AI/ML/DL enthusiast - Blockchain/DLT researcher - Mobile app (Hybrid) designer"
meta_author: Bayarsaikhan Bilguun

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: biligunb

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: biligunb
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/biligunb
  - title: stack-overflow
    url: http://stackoverflow.com/users/7934492/biligunb?tab=profile
  - title: bitbucket
    url: http://bitbucket.org/biligunb/
  - title: github
    url: http://github.com/biligunb
  - title: medium
    url: http://medium.com/@biligunb

# Postal address (add as many lines as necessary)
address:
  - line: Bayangol District 16040
  - line: Ulaanbaatar, Mongolia

# Credits content
credits: 'biligunb is online resume, created by using <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Jekyll theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty
future: true
